config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  namespace :admin do
    authenticate(:admin_user) do
      mount Flipper::UI.app(Flipper) => '/feature-flags'
    end
  end
  # mount_devise_token_auth_for 'User', at: '/api/v1/users', controllers: {
  #   registrations: 'api/v1/registrations',
  #   sessions: 'api/v1/sessions',
  #   passwords: 'api/v1/passwords'
  # }

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      get :status, to: 'health#status'

      devise_scope :user do
        resource :user, only: %i[update show]
      end
      resources :settings, only: [] do
        get :must_update, on: :collection
      end
    end
  end

  devise_for :users, path: 'users'
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root "home#index"
  get 'newcase' => 'home#new_case'
  get 'tradingcase' => 'home#trading_case'
  resources :users
  resources :cases, only: [:new, :create, :show, :index]

  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                                     :integer          not null, primary key
#  email                                  :string
#  encrypted_password                     :string           default(""), not null
#  reset_password_token                   :string
#  reset_password_sent_at                 :datetime
#  allow_password_change                  :boolean          default(FALSE), not null
#  sign_in_count                          :integer          default(0), not null
#  current_sign_in_at                     :datetime
#  last_sign_in_at                        :datetime
#  current_sign_in_ip                     :inet
#  last_sign_in_ip                        :inet
#  first_name                             :string           default("")
#  last_name                              :string           default("")
#  username                               :string           default("")
#  created_at                             :datetime         not null
#  updated_at                             :datetime         not null
#  provider                               :string           default("email"), not null
#  uid                                    :string           default(""), not null
#  tokens                                 :json
#  phone                                  :text             default("")
#  user_type                              :string
#  investor_income_response               :boolean          default(FALSE)
#  investor_net_worth_response            :boolean          default(FALSE)
#  investor_executive_response            :boolean          default(FALSE)
#  investor_business_development_response :boolean          default(FALSE)
#  case_owner_behalf                      :boolean          default(FALSE)
#  case_owner_address                     :string
#  case_owner_employment_status           :string
#  case_owner_passport                    :string
#  case_owner_dob                         :string
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_uid_and_provider      (uid,provider) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable
  include DeviseTokenAuth::Concerns::User
  enum user_type: { investor: "investor", case_owner: "case_owner" }
  enum employment_status: { employer: "employer", company: "company", unemployed: "unemployed" }
  validates :uid, uniqueness: { scope: :provider }
  validates :user_type, inclusion: { in: %w(investor case_owner) }
  validate :validate_case_owner_employment_status, if: :case_owner?
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }
  validates :phone, presence: true, uniqueness: true, format: { with: /\A\d{10}\z/, message: "must be a valid 10-digit phone number" }

  before_validation :init_uid

  RANSACK_ATTRIBUTES = %w[id email first_name last_name username sign_in_count current_sign_in_at
                          last_sign_in_at current_sign_in_ip last_sign_in_ip provider uid
                          created_at updated_at].freeze

  has_many :cases, class_name: :case, foreign_key: "author_id"

  def self.from_social_provider(provider, user_params)
    where(provider:, uid: user_params['id']).first_or_create! do |user|
      user.password = Devise.friendly_token[0, 20]
      user.assign_attributes user_params.except('id')
    end
  end

  def full_name
    return username if first_name.blank?

    "#{first_name} #{last_name}"
  end

  def case_owner?
    user_type == "case_owner"
  end

  private

  def init_uid
    self.uid = email if uid.blank? && provider == 'email'
  end

  def validate_case_owner_employment_status
    binding.pry
    unless %w(employer company unemployed).include?(employment_status)
      errors.add(:case_owner_employment_status, "must be one of 'employer', 'company', or 'unemployed'")
    end
  end
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class UsersController < Api::V1::ApiController
      before_action :auth_user

      def show; end

      def update
        current_user.update!(user_params)
        render :show
      end

      private

      def auth_user
        authorize current_user
      end

      def user_params
        params.require(:user).permit(:username, :first_name, :last_name, :email)
      end
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @user = policy_scope(User)
    @cases = Case.all.where(author_id: current_user.id) if current_user
  end
end

app/views/users/_case.html.erb
<div class="row">
  <div class="col-md-6">
    <h5><%= _case.case_type.titleize %>: <%= _case.short_description %></h5>
    <div class="d-flex flex-row justify-content-start mb-3">
      <button class="btn btn-secondary mx-1"><span class="small">Status: <%= _case.case_status.titleize %></span></button>
      <button class="btn btn-secondary mx-1"><span class="small">Risk: <%= _case&.risk_level %></span></button>
      <button class="btn btn-secondary mx-1"><span class="small">Duration: <%= _case.case_duration %></span></button>
    </div>
    <p>CASE ID: <%= _case.id %></p>
    <p>TOTAL CLAIM VALUE: US <%= number_to_currency(_case.claim_sum, unit: "$", precision: 0) %></p>
    <p>INVESTOR SHARE: <%= _case&.investor_payout %></p>
    <p>TOTAL FUNDS REQUIRED: <%= number_to_currency(_case.total_funds, unit: "$", precision: 0) %></p>
  </div>
  <div class="col-md-3 my-auto">
    <% @percentage_data = { "Funds" => (_case.total_funds.to_f / _case.claim_sum.to_f) * 100, "" => 100 - (_case.total_funds.to_f / _case.claim_sum.to_f), } %>
    <%= pie_chart @percentage_data, donut: true, legend: false %>
  </div>
  <div class="col-md-3 text-right my-auto">
    <button class="btn btn-primary">Update</button>
  </div>
</div>
<hr>

app/views/users/_form_modal.html.erb
<div class="modal fade" id="caseFormModal" tabindex="-1" role="dialog" aria-labelledby="caseFormModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-center font-weight-bold" id="caseFormModalLabel">List New Case</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with(model: Case.new, url: cases_path, method: :post, class: "px-5", id: "caseForm", multipart: true, remote: true) do |form| %>
          <div id="errorMessages" class="row"></div>
          <div id="page1">
            <%= render 'cases/form', form: form %>
          </div>

          <div id="page2" style="display: none;">
            <%= render 'payouts_and_terms', form: form %>
          </div>
          <%= form.submit 'Create Case', class: 'btn btn-success', id: 'submitBtn' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const form = document.getElementById("caseForm");
    const errorMessages = document.getElementById("errorMessages");

    form.addEventListener("submit", function (event) {
      event.preventDefault();
      
      const formData = new FormData(form);

      fetch(form.action, {
        method: "POST",
        headers: {
          "X-CSRF-Token": document.querySelector('meta[name="csrf-token"]').getAttribute('content')
        },
        body: formData,
      })
      .then(response => response.json())
      .then(data => {
        if (data.success) {
          document.getElementById("caseFormModal").classList.remove("show");
          document.getElementsByClassName("modal-backdrop")[0].classList.remove("show");
        } else {
          errorMessages.innerHTML = `<div class="alert alert-danger col-12">${data.message}</div>`;
        }
      })
      .catch(error => {
        console.error("Error:", error);
      });
    });
  });
</script>

app/views/users/_get_started.html.erb
<div class="text-center my-5">
  <h5 class="font-weight-bold">Get Started</h5>
  <div class="mx-auto my-auto" style="position: relative; width: 150px; height: 150px; border-radius: 50%; background-color: #eee;" >
    <div style="position: absolute; top: 50%; left: calc(50% - 20px); transform: translateY(-50%);">
      <i class="fa fa-wallet h1 text-primary"></i>
    </div>
  </div>

  <p class="my-4">Only few steps to start your investment!</p>

  <a href="<%= new_user_registration_path %>" class="btn btn-primary mb-3 btn-lg font-weight-bold">Sign Up</a>
  <p>Already have an account? <a href="<%= new_user_session_path %>">Sign In</a></p>
</div>

app/views/users/_payouts_and_terms.html.erb
<button type="button" class="btn btn-outline-primary" id="prevPageBtn"><i class="fa fa-arrow-left mr-3"></i> Back</button>

<div class="text-center">
  <div class="h4 font-weight-bold">Payout Distribution</div>
  <div class="d-flex flex-row justify-content-center my-5">
    <div class="d-flex flex-column mx-5">
      <span class="font-weight-bold">Plaintiff</span>
      <span class="font-weight-bold">60%</span>
    </div>
  
    <div class="d-flex flex-column mx-5">
      <span class="font-weight-bold">Investor</span>
      <span class="font-weight-bold">30%</span>
    </div>
  
    <div class="d-flex flex-column mx-5">
      <span class="font-weight-bold">Plaintiff</span>
      <span class="font-weight-bold">60%</span>
    </div>
  </div>
</div>

<%= form.label :terms_and_conditions, class: "h5 font-weight-bold text-center w-100 my-5" %>
<div class="row">
  <textarea class="form-control col-sm-12" readonly="true" row>
    <%= Case::CASE_TERM_AND_CONDITION %>
  </textarea>
  <div class="form-check my-3">
    <input class="form-check-input" type="checkbox" value="" id="terms_and_conditions">
    <label class="form-check-label" for="terms_and_conditions">
      I have read the terms and conditions and agree to continue
    </label>
  </div>
</div>

<div class="text-center my-5">
  <button form="caseFormModal" type="submit" class="btn btn-primary" id="nextPageBtn">List Case <i class="fa fa-arrow-right ml-3"></i></button>
</div>

app/views/users/index.html.erb
<div class="card my-4">
  <% if current_user %>
  <ul class="nav nav-tabs custom-tabs" role="tablist">
    <li class="nav-item py-2">
      <a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab"><i class="fa fa-list mr-4"></i>My Cases</a>
    </li>
    <li class="nav-item py-2">
      <a class="nav-link" data-toggle="tab" href="#tabs-2" role="tab"><i class="fa fa-archive mr-4"></i>Draft</a>
    </li>
    <button class="btn btn-primary position-absolute right-1 top-1" style="right: 1%; top: 1%;" data-toggle="modal"   data-target="#caseFormModal">
      <i class="fa fa-plus-square"></i>
    </button>
  </ul><!-- Tab panes -->
  <div class="tab-content">
    <div class="tab-pane active" id="tabs-1" role="tabpanel">
      <div class="p-4">
        
          <% @cases.each do |_case| %>
            <%= render partial: "case", locals: {_case: _case} %>
          <% end %>

          <% if @cases.count == 0 %>
            <div class="text-center">
              No data
            </div>
          <% end %>
          <%= render 'form_modal' %>
        
      </div>
    </div>
    <div class="tab-pane" id="tabs-2" role="tabpanel">
      <div class="p-4">
        Second Panel
      </div>
    </div>
  </div>
  <% else %>
    <%= render "get_started" %>
  <% end %>
</div>